version: '2'
services:
  rabbitmq:
    image: rabbitmq
    networks:
      default:
        aliases:
          - rabbitmq
  app:
    depends_on:
      - rabbitmq
    image: portal/app
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DEV_MODE: "true"
  aui-theme-plugin:
    depends_on:
      - app
    image: portal/aui-theme-plugin


networks:
  default:
    external:
      name: framework
