version: '2'
services:
  rabbitmq:
    image: rabbitmq
    networks:
      default:
        aliases:
          - rabbitmq
  dockui-proxy:
    depends_on:
      - rabbitmq
    image: dockui/proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DEV_MODE: "true"

networks:
  default:
    external:
      name: framework
