version: '2'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672
    networks:
      app:
        aliases:
          - rabbitmq
  web:
    depends_on:
      - rabbitmq
    build: .
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app
  decorator:
    depends_on:
      - web
    build: ./bundled-plugins/app-decorator/
    ports:
      - "8080"
    networks:
      - app
  resources:
    depends_on:
      - web
    build: ./bundled-plugins/app-resources/
    ports:
      - "8080"
    networks:
      - app
  demo-plugin:
    depends_on:
      - decorator
      - resources
    build: ./bundled-plugins/demo-plugin/
    ports:
      - "8080"
    networks:
      - app

networks:
  app:
