version: '2'
services:
  rabbitmq:
    image: rabbitmq
    networks:
      default:
        aliases:
          - rabbitmq
  dockui-proxy:
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DEV_MODE: "true"

networks:
  default:
    external:
      name: framework
