version: "3"

services:
  node-app:
    image: dockui/app
    networks:
      - dockui
    environment:
      - DOCKUI_WEB_PORT=8443
      - DOCKUI_WEB_SSL_CERT=/tmp/dockui.server.cert
      - DOCKUI_WEB_SSL_KEY=/tmp/dockui.server.key
      - DOCKUI_WEB_SCHEME=https
      - DOCKUI_STORE_TYPE=lokijs
      - DOCKUI_STORE_DB_FILENAME=/app/loki.db
      - DOCKUI_LOGGING_LEVEL=debug
      - DOCKUI_DOCKER_SELECTOR_LABEL=DOCKUI_APP
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - 8443:8443
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

networks:
  dockui:
    driver: overlay
