# Here you specify a name, key and version of your plugin which is used
# by the plugin service to instantiate a unique Plugin at runtime
# plugins are linked to their docker containers so when the container goes down the plugin dies
name: "AUI Theme"
key: "aui-theme-plugin"

# Modules do the work for the plugin. See the various types for explanation of what they do
modules:

    - type : "webitem"
      name: "Action Button"
      key: "action-button"
      link: "#"
      location: "app.home.header.primary.webitems"
      weight: 10
      text: "Action"

    - type : "webitem"
      name: "Site Branding Banner Title"
      key: "branding-header-title"
      link: "/"
      location: "app.home.branding.title"
      weight: 10
      text: "Dock UI"

  # Webpages are entire html pages which can optionally be decorated by a specific decorator
  # and additionally specify resourcesFor meta to have static resources injected from contributing plugins
  # If its a decorator then we can add the optional field decorator: true
    - type : "webpage"
      name : "Home Decorator"
      key : "app-home-decorator"
      path : "/home"
      decorator: true

  # Web resources define static resources that you can contribute to existing webpages
  # by giving a context. The context is used by webpages via the resourcesFor Meta tag

    - type : "webresources"
      name : "App home webresources"
      key : "app-home-resources"
      base : "/resources/"
      resources :
        - type: "css"
          path : "libs/aui/6.0.6/aui.min.css"
        - type: "js"
          path : "libs/aui/6.0.6/aui.min.js"
        - type: "js"
          path : "app.home.decorator.js"
        - type: "css"
          path : "app.home.decorator.css"
      context : "app.home"
