# Here yo uspecify a name, key and version of your plugin which is used
# by the plugin service to instantiate a unique Plugin at runtime
# plugins are linked to their docker containers so when the container goes down the plugin dies
name: "Tutorial Plugin"
key: "tutorial-plugin"

# Modules do the work for the plugin. See the various types for explanation of what they do
modules:

  # Routes are a way to rewrite more readable urls for a given webpage or resource
    - type : "route"
      name: "Tutorial route"
      key: "tutorial-route"
      routes:
        - "/tutorial"
      path: "/plugins/tutorial-plugin/webpages/tutorial"

  # Webitems are links that you can insert in various places in the webapp
  # Locations are defined within the templates themselves
    - type : "webitem"
      name: "Tutorial link"
      key: "tutorial-link"
      link: "/tutorial"
      location: "app.home.header.primary.dropdown.webitems"
      weight: 10
      text: "5 Min Tutorial"

  # Webfragments are html partials which will be injected into the specified location
  # for example to show a widget on an existing page ( like AUI dialog2 hidden dialog html )
  # the path is to the served html template, and the fragment is a CSS selector for a single element to
  # use as the actual fragment for this module


  # Webpages are entire html pages which can optionally be decorated by a specific decorator
  # and additionally specify resourcesFor meta to have static resources injected from contributing plugins
    - type : "webpage"
      name : "Tutorial page"
      key : "tutorial"
      path : "/tutorial"

  # Rest modules define a single endpoint that is simply proxied by the main api gateway

  # Web resources define static resources that you can contribute to existing webpages
  # by giving a context. The context is used by webpages via the resourcesFor Meta tag
    - type : "webresources"
      name : "Tutorial webresources"
      key : "tutorial-resources"
      base : "/resources/"
      resources :
        - type: "js"
          path : "tutorial.javascript.js"
        - type: "css"
          path : "tutorial.style.css"
      context : "plugin.tutorial"
