version: '2'
services:

  rabbitmq:
    image: rabbitmq
    networks:
      default:
        aliases:
          - rabbitmq

  dockui:
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    command: nodemon -e js,css,html,yml,json --ignore "bundled-plugins" App.js
    environment:
      DEV_MODE: "true"

  dockui-plugin-aui-theme:
    depends_on:
      - dockui
    build:
      context: ./bundled-plugins/aui-theme-plugin
      dockerfile: Dockerfile
    volumes:
      - ./bundled-plugins/aui-theme-plugin:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon -e js,css,html,yml,json Plugin.js

  dockui-plugin-tour:
    depends_on:
      - dockui
    build:
      context: ./bundled-plugins/tour-plugin
      dockerfile: Dockerfile
    volumes:
      - ./bundled-plugins/tour-plugin:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon -e js,css,html,yml,json Plugin.js

  dockui-plugin-docs:
    depends_on:
      - dockui
    build:
      context: ./bundled-plugins/docs-plugin
      dockerfile: Dockerfile
    volumes:
      - ./bundled-plugins/docs-plugin:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon -e js,css,html,yml,json Plugin.js

  dockui-plugin-tutorial:
    depends_on:
      - dockui
    build:
      context: ./bundled-plugins/tutorial-plugin
      dockerfile: Dockerfile
    volumes:
      - ./bundled-plugins/tutorial-plugin:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon -e js,css,html,yml,json Plugin.js

  dockui-plugin-form-auth:
    depends_on:
      - dockui
    build:
      context: ./bundled-plugins/form-auth-plugin
      dockerfile: Dockerfile
    volumes:
      - ./bundled-plugins/form-auth-plugin:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon -e js,css,html,yml,json Plugin.js

  dockui-plugin-admin:
    depends_on:
      - dockui
    build:
      context: ./bundled-plugins/admin-plugin
      dockerfile: Dockerfile
    volumes:
      - ./bundled-plugins/admin-plugin:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon -e js,css,html,yml,json Plugin.js

networks:
  default:
    external:
      name: framework
