# Here yo uspecify a name, key and version of your plugin which is used
# by the plugin service to instantiate a unique Plugin at runtime
# plugins are linked to their docker containers so when the container goes down the plugin dies
name: "Form Auth Plugin"
key: "form-auth-plugin"

# TODO: Figure out how to add auth to all module types

# Modules do the work for the plugin. See the various types for explanation of what they do
modules:

  # Auth provider provide capabilities to authenticate the user session
  # As providers are chained, Weight represents where in the order this will fire


  # Routes are a way to rewrite more readable urls for a given webpage or resource
    - type : "route"
      name: "Login route"
      key: "login-route"
      routes:
        - "/login*"
      path: "/plugins/form-auth-plugin/webpages/login"

  # Webitems are links that you can insert in various places in the webapp
  # Locations are defined within the templates themselves

  # Webfragments are html partials which will be injected into the specified location
  # for example to show a widget on an existing page ( like AUI dialog2 hidden dialog html )
  # the path is to the served html template, and the fragment is a CSS selector for a single element to
  # use as the actual fragment for this module


  # Webpages are entire html pages which can optionally be decorated by a specific decorator
  # and additionally specify resourcesFor meta to have static resources injected from contributing plugins
    - type : "webpage"
      name : "Login page"
      key : "login"
      path : "/login"

  # Rest modules define a single endpoint that is simply proxied by the main api gateway

  # Web resources define static resources that you can contribute to existing webpages
  # by giving a context. The context is used by webpages via the resourcesFor Meta tag
